project:
  type: book

book:
  title: "Eerste probeersel"
  author: "Fontys ICT sem1"
  date: "9/20/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - README.qmd
    - ../docs/computational/readme.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

cover-image: "/Users/croc02/git/sem1/softwarematerial/myFirstQBook"
